-- Schema inicial (baseline). Gerado a partir das entidades com o dialeto do
-- PostgreSQL e revisado à mão. Mudança de schema daqui em diante é V2, V3...
-- nunca editar este arquivo depois de aplicado.

create table categorias (
    id   bigint generated by default as identity primary key,
    nome varchar(60) not null,
    tipo varchar(10) not null check (tipo in ('RECEITA', 'DESPESA')),
    constraint uk_categorias_nome unique (nome)
);

create table transacoes (
    id           bigint generated by default as identity primary key,
    descricao    varchar(140)   not null,
    valor        numeric(12, 2) not null check (valor > 0),
    tipo         varchar(10)    not null check (tipo in ('RECEITA', 'DESPESA')),
    data         date           not null,
    categoria_id bigint         not null,
    criada_em    timestamp(6) with time zone not null,
    constraint fk_transacoes_categoria foreign key (categoria_id) references categorias (id)
);

-- Listagem e resumo filtram por período; a remoção de categoria checa uso por categoria_id.
create index idx_transacoes_data on transacoes (data);
create index idx_transacoes_categoria on transacoes (categoria_id);
